apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-beako
  namespace: sanctuary-dev
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-beako
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
