apiVersion: apps/v1
kind: Deployment
metadata:
  name: gospel-db
  namespace: sanctuary-dev
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: gospel-db
    app.kubernetes.io/version: "16"
    app.kubernetes.io/part-of: pleiades-infra
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kubectl
    pleiades.watchtower/identity: beako
    pleiades.watchtower/environment: sanctuary-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/instance: gospel-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: gospel-db
        app.kubernetes.io/version: "16"
        app.kubernetes.io/part-of: pleiades-infra
        app.kubernetes.io/component: database
        app.kubernetes.io/managed-by: kubectl
        pleiades.watchtower/identity: beako
        pleiades.watchtower/environment: sanctuary-dev
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-beako
              key: db_password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-beako
              key: db_user
        - name: POSTGRES_DB
          value: gospel-db
        image: postgres:16
        name: gospel-db
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: gospel-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: gospel-data
        persistentVolumeClaim:
          claimName: pvc-beako