apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-beako
  labels:
    app.kubernetes.io/part-of: pleiades-infra
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: kubectl
    pleiades.watchtower/identity: beako
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer